version: "3"

services:
  nginx:
    image: nginx:1.15
    restart: always
    volumes:
      - ./sites.conf:/etc/nginx/conf.d/sites.conf
    ports:
      - "80:80"
    networks:
      - ndb

  docker-laravel:
    build: ./server
    # links:
    #   - db
    networks:
      - ndb
    depends_on:
      - db
      - redis

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    restart: always
    environment:
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - ndb

  redis:
    image: redis
    restart: always

  phpmyadmin:
    # image: corbinu/docker-phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    # links:
    #   - db
    networks:
      - ndb
    ports:
      - 9000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=homestead
      - PMA_PASSWORD=secret

networks:
    ndb:
        driver: bridge 