version: '3.4'

services:

  medico:
    # build: ./
    image: nginx
    container_name: medico_web
    restart: unless-stopped
    environment:
      - DB_HOST=db-medico
      - DB_PORT=8082
      - DB_USER=medico
      - DB_NAME=medico
      - DB_PASSWORD=medico#123
      - URL=http://35.237.186.164:8020
      - PORT=8000
    ports:
      - "8020:8000"
    links:
      - db-medico
    depends_on:
      - db-medico
    networks:
      - medico_net
            
  db-medico:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "8082:3306"
    volumes:
      - db-medico:/var/lib/mysql_medico
    environment:
      - MYSQL_ROOT_PASSWORD=medico#12345
      - MYSQL_PASSWORD=medico#123
      - MYSQL_DATABASE=medico
      - MYSQL_USER=medico
    networks:
      - medico_net

  api:
    restart: always
    depends_on:
      - db-medico
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
      - .:/ts2/api
      - /ts2/api/node_modules
    environment:
      - HOST=api
      - NODE_ENV=development
      - PORT=5000
      - TYPEORM_CONNECTION=mysql
      - TYPEORM_HOST=mysql
      - TYPEORM_PORT=3326
      - TYPEORM_USERNAME=stagiop
      - TYPEORM_PASSWORD=h3lloWorld
      - TYPEORM_DATABASE=stagiop
      - TYPEORM_SYNCHRONIZE=true
      - TYPEORM_ENTITIES=src/domain/entity/*.js
      - TYPEORM_LOGGING=true
      - MONGODB_URI=${MONGODB_URI}
    ports:
      - 5000:5000

networks:
  medico_net:
    driver: bridge

volumes:
  db-medico:
